services:
  postgres:
    image: postgres:12.3-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - 5433:5432
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres: